# Generated by Django 3.0.2 on 2020-04-01 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_files',
            field=models.FileField(blank=True, null=True, upload_to='orders_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
    ]
